name: "WereWolf"
api: 1.20.6
version: "0.6"
main: "me.a8kj.ww.internal.plugin.EventMobPlugin"
author: "a8kj7sea"
description: "a custom project made for client called astrotix by a8kj7sea"
author-site: "https://github.com/a8kj7sea"
depends:
  - WorldGuard
  - MythicsMobs

commands:
  werewolf:
    permission: "werewolf-plugin.admin"
    description: "main command"
    aliases: ["lg", "wfevent", "werewolf-event", "wwevent"]